image:
  name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_VAR_gitlab_token: ${GITLAB_ACCESS_TOKEN}
  AWS_ACCESS_KEY_ID: ${MY_AWS_KEY}
  AWS_SECRET_ACCESS_KEY : ${MY_AWS_ACCESS_KEY}
  AWS_DEFAULT_REGION: "ap-southeast-1"
  ENVIRONMENT: "dev"

cache:
  paths:
    - .terraform

before_script:
  - terraform -chdir=infra/segment/visitorapp
  - terraform --version
  - terraform init -backend-config="../../config/visitorapp/backend-'$ENVIRONMENT'.tfvars"

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform -chdir=infra/segment/visitorapp
    - terraform plan -var-file="../../config/visitorapp/'$ENVIRONMENT'.tfvars"
  dependencies:
    - validate
  
apply:
  stage: apply
  script:
    - terraform -chdir=infra/segment/visitorapp
    - terraform apply -var-file="../../config/visitorapp/'$ENVIRONMENT'.tfvars"
  dependencies:
    - plan
  when: manual

destroy: 
  stage: destroy
  script:
    - terraform destroy -var-file="../../config/visitorapp/'$ENVIRONMENT'.tfvars"
  when: manual



